--- #YAML:1.0
name: Devel-ebug
version: 0.32
author:
  - Leon Brocard, C<< <acme@astray.com> >>
abstract: A simple, extensible Perl debugger
license: perl
requires:
  Class::Accessor::Chained::Fast: 0
  HTTP::Server::Simple::CGI: 0
  IO::Socket::INET: 0
  PPI: 0
  PPI::HTML: 0
  PPI::Lexer: 0
  PadWalker: 0
  Proc::Background: 0
  Storable: 0
  String::Koremutake: 0
  Template: 0
  Test::Differences: 0
  Test::Expect: 0
  Test::More: 0
  YAML: 0
provides:
  DB:
    file: lib/Devel/ebug.pm
    version: 0.32
  Devel::ebug:
    file: lib/Devel/ebug.pm
    version: 0.32
  filename:
    file: lib/Devel/ebug.pm
    version: 0.32
generated_by: Module::Build version 0.2605
