---
name: Devel-ebug
version: 0.40
author:
  - 'Leon Brocard, C<< <acme@astray.com> >>'
abstract: 'A simple, extensible Perl debugger'
license: perl
requires:
  Carp: 0
  Catalyst: 5.02
  Catalyst::Plugin::Static: 0.07
  Catalyst::View::TT: 0.11
  Class::Accessor::Chained::Fast: 0
  Devel::StackTrace: 0
  File::Find: 0
  HTML::Prototype: 0
  HTTP::Server::Simple::CGI: 0
  IO::Socket::INET: 0
  List::Util: 0
  Module::Pluggable: 0
  PPI: 0
  PPI::HTML: 0
  PPI::Lexer: 0
  PadWalker: 0
  Path::Class: 0
  Proc::Background: 0
  Scalar::Util: 0
  Storable: 0
  String::Koremutake: 0
  Template: 0
  Test::Differences: 0
  Test::Expect: 0
  Test::More: 0
  Test::WWW::Mechanize::Catalyst: 0.31
  YAML: 0.39
provides:
  DB:
    file: lib/Devel/ebug/Backend/Plugin/Eval.pm
    version: 0.40
  DB::fake:
    file: lib/Devel/ebug/Backend.pm
    version: 0.40
  Devel::ebug:
    file: lib/Devel/ebug.pm
    version: 0.40
  Devel::ebug::Backend::Plugin::ActionPoints:
    file: lib/Devel/ebug/Backend/Plugin/ActionPoints.pm
  Devel::ebug::Backend::Plugin::Basic:
    file: lib/Devel/ebug/Backend/Plugin/Basic.pm
  Devel::ebug::Backend::Plugin::Codelines:
    file: lib/Devel/ebug/Backend/Plugin/Codelines.pm
  Devel::ebug::Backend::Plugin::Commands:
    file: lib/Devel/ebug/Backend/Plugin/Commands.pm
  Devel::ebug::Backend::Plugin::Eval:
    file: lib/Devel/ebug/Backend/Plugin/Eval.pm
  Devel::ebug::Backend::Plugin::Filenames:
    file: lib/Devel/ebug/Backend/Plugin/Filenames.pm
  Devel::ebug::Backend::Plugin::Output:
    file: lib/Devel/ebug/Backend/Plugin/Output.pm
  Devel::ebug::Backend::Plugin::Pad:
    file: lib/Devel/ebug/Backend/Plugin/Pad.pm
  Devel::ebug::Backend::Plugin::Ping:
    file: lib/Devel/ebug/Backend/Plugin/Ping.pm
  Devel::ebug::Backend::Plugin::Run:
    file: lib/Devel/ebug/Backend/Plugin/Run.pm
  Devel::ebug::Backend::Plugin::StackTrace:
    file: lib/Devel/ebug/Backend/Plugin/StackTrace.pm
  Devel::ebug::Backend::Plugin::Subroutine:
    file: lib/Devel/ebug/Backend/Plugin/Subroutine.pm
  Devel::ebug::Build:
    file: lib/Devel/ebug/Build.pm
  Devel::ebug::Console:
    file: lib/Devel/ebug/Console.pm
  Devel::ebug::HTTP:
    file: lib/Devel/ebug/HTTP.pm
  Devel::ebug::HTTP::View::TT:
    file: lib/Devel/ebug/HTTP/View/TT.pm
  Devel::ebug::Plugin::ActionPoints:
    file: lib/Devel/ebug/Plugin/ActionPoints.pm
  Devel::ebug::Plugin::Basic:
    file: lib/Devel/ebug/Plugin/Basic.pm
  Devel::ebug::Plugin::Codelines:
    file: lib/Devel/ebug/Plugin/Codelines.pm
  Devel::ebug::Plugin::Eval:
    file: lib/Devel/ebug/Plugin/Eval.pm
  Devel::ebug::Plugin::Filenames:
    file: lib/Devel/ebug/Plugin/Filenames.pm
  Devel::ebug::Plugin::Output:
    file: lib/Devel/ebug/Plugin/Output.pm
  Devel::ebug::Plugin::Pad:
    file: lib/Devel/ebug/Plugin/Pad.pm
  Devel::ebug::Plugin::Run:
    file: lib/Devel/ebug/Plugin/Run.pm
  Devel::ebug::Plugin::StackTrace:
    file: lib/Devel/ebug/Plugin/StackTrace.pm
  Devel::ebug::Plugin::Subroutine:
    file: lib/Devel/ebug/Plugin/Subroutine.pm
  filename:
    file: lib/Devel/ebug.pm
    version: 0.40
generated_by: Module::Build version 0.2605
