--- #YAML:1.0
name: Devel-ebug
version: 0.29
author:
  - Leon Brocard, C<< <acme@astray.com> >>
abstract: A simple, extensible Perl debugger
license: perl
requires:
  Class::Accessor::Chained::Fast: 0
  IO::Socket::INET: 0
  PadWalker: 0
  Proc::Background: 0
  Storable: 0
  Test::More: 0
provides:
  DB:
    file: lib/Devel/ebug.pm
    version: 0.29
  Devel::ebug:
    file: lib/Devel/ebug.pm
    version: 0.29
  filename:
    file: lib/Devel/ebug.pm
    version: 0.29
generated_by: Module::Build version 0.2605
